// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$74 {

    static final FunctionDescriptor crypto_verify_32_bytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_verify_32_bytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_verify_32_bytes",
        "()J",
        constants$74.crypto_verify_32_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_32$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_verify_32$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_verify_32",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$74.crypto_verify_32$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_64_bytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_verify_64_bytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_verify_64_bytes",
        "()J",
        constants$74.crypto_verify_64_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_64$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_verify_64$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_verify_64",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$74.crypto_verify_64$FUNC, false
    );
    static final FunctionDescriptor randombytes_seedbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle randombytes_seedbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "randombytes_seedbytes",
        "()J",
        constants$74.randombytes_seedbytes$FUNC, false
    );
    static final FunctionDescriptor randombytes_buf$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_LONG
    );
    static final MethodHandle randombytes_buf$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "randombytes_buf",
        "(Ljdk/incubator/foreign/MemoryAddress;J)V",
        constants$74.randombytes_buf$FUNC, false
    );
}


