// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$35 {

    static final FunctionDescriptor crypto_kdf_blake2b_bytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_blake2b_bytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_blake2b_bytes_max",
        constants$35.crypto_kdf_blake2b_bytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_contextbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_blake2b_contextbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_blake2b_contextbytes",
        constants$35.crypto_kdf_blake2b_contextbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_blake2b_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_blake2b_keybytes",
        constants$35.crypto_kdf_blake2b_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_derive_from_key$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_kdf_blake2b_derive_from_key$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_blake2b_derive_from_key",
        constants$35.crypto_kdf_blake2b_derive_from_key$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_bytes_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_bytes_min$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_bytes_min",
        constants$35.crypto_kdf_bytes_min$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_bytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_bytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_bytes_max",
        constants$35.crypto_kdf_bytes_max$FUNC, false
    );
}


