// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$92 {

    static final FunctionDescriptor crypto_core_ristretto255_scalar_random$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_random$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_random",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.crypto_core_ristretto255_scalar_random$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_invert$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_invert$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_invert",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$92.crypto_core_ristretto255_scalar_invert$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_negate$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_negate$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_negate",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.crypto_core_ristretto255_scalar_negate$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_complement$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_complement$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_complement",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.crypto_core_ristretto255_scalar_complement$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_add$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_add$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_add",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.crypto_core_ristretto255_scalar_add$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_sub$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ristretto255_scalar_sub$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ristretto255_scalar_sub",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$92.crypto_core_ristretto255_scalar_sub$FUNC, false
    );
}


