// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$48 {

    static final FunctionDescriptor crypto_pwhash_argon2id_memlimit_sensitive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_memlimit_sensitive$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_memlimit_sensitive",
        constants$48.crypto_pwhash_argon2id_memlimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle crypto_pwhash_argon2id$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id",
        constants$48.crypto_pwhash_argon2id$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_str$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_pwhash_argon2id_str$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_str",
        constants$48.crypto_pwhash_argon2id_str$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_str_verify$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_pwhash_argon2id_str_verify$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_str_verify",
        constants$48.crypto_pwhash_argon2id_str_verify$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_str_needs_rehash$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_pwhash_argon2id_str_needs_rehash$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_str_needs_rehash",
        constants$48.crypto_pwhash_argon2id_str_needs_rehash$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_alg_argon2i13$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle crypto_pwhash_alg_argon2i13$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_alg_argon2i13",
        constants$48.crypto_pwhash_alg_argon2i13$FUNC, false
    );
}


