// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$61 {

    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_headerbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_headerbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_headerbytes",
        constants$61.crypto_secretstream_xchacha20poly1305_headerbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_keybytes",
        constants$61.crypto_secretstream_xchacha20poly1305_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_messagebytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_messagebytes_max",
        constants$61.crypto_secretstream_xchacha20poly1305_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_tag_message$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_tag_message$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_tag_message",
        constants$61.crypto_secretstream_xchacha20poly1305_tag_message$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_tag_push$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_tag_push$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_tag_push",
        constants$61.crypto_secretstream_xchacha20poly1305_tag_push$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_tag_rekey$FUNC = FunctionDescriptor.of(Constants$root.C_CHAR$LAYOUT);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_tag_rekey$MH = RuntimeHelper.downcallHandle(
        "crypto_secretstream_xchacha20poly1305_tag_rekey",
        constants$61.crypto_secretstream_xchacha20poly1305_tag_rekey$FUNC, false
    );
}


