// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$80 {

    static final FunctionDescriptor sodium_bin2hex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sodium_bin2hex$MH = RuntimeHelper.downcallHandle(
        "sodium_bin2hex",
        constants$80.sodium_bin2hex$FUNC, false
    );
    static final FunctionDescriptor sodium_hex2bin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sodium_hex2bin$MH = RuntimeHelper.downcallHandle(
        "sodium_hex2bin",
        constants$80.sodium_hex2bin$FUNC, false
    );
    static final FunctionDescriptor sodium_base64_encoded_len$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sodium_base64_encoded_len$MH = RuntimeHelper.downcallHandle(
        "sodium_base64_encoded_len",
        constants$80.sodium_base64_encoded_len$FUNC, false
    );
    static final FunctionDescriptor sodium_bin2base64$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sodium_bin2base64$MH = RuntimeHelper.downcallHandle(
        "sodium_bin2base64",
        constants$80.sodium_bin2base64$FUNC, false
    );
    static final FunctionDescriptor sodium_base642bin$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle sodium_base642bin$MH = RuntimeHelper.downcallHandle(
        "sodium_base642bin",
        constants$80.sodium_base642bin$FUNC, false
    );
    static final FunctionDescriptor sodium_mlock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sodium_mlock$MH = RuntimeHelper.downcallHandle(
        "sodium_mlock",
        constants$80.sodium_mlock$FUNC, false
    );
}


