// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$3 {

    static final FunctionDescriptor crypto_aead_aes256gcm_encrypt_detached$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_encrypt_detached$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_encrypt_detached",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_encrypt_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_decrypt_detached$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_decrypt_detached$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_decrypt_detached",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_decrypt_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_beforenm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_beforenm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_beforenm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_beforenm$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_encrypt_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_encrypt_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_encrypt_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_encrypt_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_decrypt_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_decrypt_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_decrypt_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_decrypt_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_encrypt_detached_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_encrypt_detached_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_encrypt_detached_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$3.crypto_aead_aes256gcm_encrypt_detached_afternm$FUNC, false
    );
}


