// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$39 {

    static final FunctionDescriptor crypto_onetimeauth_poly1305_verify$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_poly1305_verify$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_poly1305_verify",
        constants$39.crypto_onetimeauth_poly1305_verify$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_poly1305_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_poly1305_init$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_poly1305_init",
        constants$39.crypto_onetimeauth_poly1305_init$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_poly1305_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_poly1305_update$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_poly1305_update",
        constants$39.crypto_onetimeauth_poly1305_update$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_poly1305_final$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_poly1305_final$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_poly1305_final",
        constants$39.crypto_onetimeauth_poly1305_final$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_poly1305_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_poly1305_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_poly1305_keygen",
        constants$39.crypto_onetimeauth_poly1305_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_statebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_onetimeauth_statebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_statebytes",
        constants$39.crypto_onetimeauth_statebytes$FUNC, false
    );
}


