// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$84 {

    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_publickeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_publickeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_publickeybytes",
        constants$84.crypto_box_curve25519xchacha20poly1305_publickeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_secretkeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_secretkeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_secretkeybytes",
        constants$84.crypto_box_curve25519xchacha20poly1305_secretkeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_beforenmbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_beforenmbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_beforenmbytes",
        constants$84.crypto_box_curve25519xchacha20poly1305_beforenmbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_noncebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_noncebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_noncebytes",
        constants$84.crypto_box_curve25519xchacha20poly1305_noncebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_macbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_macbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_macbytes",
        constants$84.crypto_box_curve25519xchacha20poly1305_macbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_messagebytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_messagebytes_max",
        constants$84.crypto_box_curve25519xchacha20poly1305_messagebytes_max$FUNC, false
    );
}


