// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$60 {

    static final FunctionDescriptor crypto_stream_chacha20_ietf_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_chacha20_ietf_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_chacha20_ietf_messagebytes_max",
        "()J",
        constants$60.crypto_stream_chacha20_ietf_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_stream_chacha20_ietf$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_chacha20_ietf",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$60.crypto_stream_chacha20_ietf$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf_xor$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_stream_chacha20_ietf_xor$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_chacha20_ietf_xor",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$60.crypto_stream_chacha20_ietf_xor$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf_xor_ic$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle crypto_stream_chacha20_ietf_xor_ic$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_chacha20_ietf_xor_ic",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$60.crypto_stream_chacha20_ietf_xor_ic$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf_keygen$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_stream_chacha20_ietf_keygen$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_chacha20_ietf_keygen",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$60.crypto_stream_chacha20_ietf_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_secretstream_xchacha20poly1305_abytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretstream_xchacha20poly1305_abytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretstream_xchacha20poly1305_abytes",
        "()J",
        constants$60.crypto_secretstream_xchacha20poly1305_abytes$FUNC, false
    );
}


