// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$0 {

    static final FunctionDescriptor sodium_version_string$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle sodium_version_string$MH = RuntimeHelper.downcallHandle(
        "sodium_version_string",
        constants$0.sodium_version_string$FUNC, false
    );
    static final FunctionDescriptor sodium_library_version_major$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_library_version_major$MH = RuntimeHelper.downcallHandle(
        "sodium_library_version_major",
        constants$0.sodium_library_version_major$FUNC, false
    );
    static final FunctionDescriptor sodium_library_version_minor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_library_version_minor$MH = RuntimeHelper.downcallHandle(
        "sodium_library_version_minor",
        constants$0.sodium_library_version_minor$FUNC, false
    );
    static final FunctionDescriptor sodium_library_minimal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_library_minimal$MH = RuntimeHelper.downcallHandle(
        "sodium_library_minimal",
        constants$0.sodium_library_minimal$FUNC, false
    );
    static final FunctionDescriptor sodium_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_init$MH = RuntimeHelper.downcallHandle(
        "sodium_init",
        constants$0.sodium_init$FUNC, false
    );
    static final FunctionDescriptor sodium_set_misuse_handler$handler$FUNC = FunctionDescriptor.ofVoid();
}


