// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$86 {

    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_beforenm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_beforenm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_beforenm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.crypto_box_curve25519xchacha20poly1305_beforenm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_easy_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_easy_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_easy_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.crypto_box_curve25519xchacha20poly1305_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_open_easy_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_open_easy_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_open_easy_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.crypto_box_curve25519xchacha20poly1305_open_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_detached_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_detached_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_detached_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.crypto_box_curve25519xchacha20poly1305_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_open_detached_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_open_detached_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_open_detached_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$86.crypto_box_curve25519xchacha20poly1305_open_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_sealbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_sealbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_sealbytes",
        "()J",
        constants$86.crypto_box_curve25519xchacha20poly1305_sealbytes$FUNC, false
    );
}


