// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$104 {

    static final MemorySegment crypto_shorthash_PRIMITIVE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("siphash24");
    static final MemorySegment crypto_sign_PRIMITIVE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("ed25519");
    static final MemorySegment crypto_stream_PRIMITIVE$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("xsalsa20");
    static final MemorySegment crypto_pwhash_scryptsalsa208sha256_STRPREFIX$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$7$");
}


