// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$69 {

    static final FunctionDescriptor crypto_sign_publickeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_sign_publickeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_publickeybytes",
        constants$69.crypto_sign_publickeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_secretkeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_sign_secretkeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_secretkeybytes",
        constants$69.crypto_sign_secretkeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_messagebytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_sign_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_messagebytes_max",
        constants$69.crypto_sign_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_primitive$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_sign_primitive$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_primitive",
        constants$69.crypto_sign_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_seed_keypair$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_seed_keypair$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_seed_keypair",
        constants$69.crypto_sign_seed_keypair$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_keypair$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_keypair$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_keypair",
        constants$69.crypto_sign_keypair$FUNC, false
    );
}


