// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$104 {

    static final MemorySegment crypto_shorthash_PRIMITIVE$SEGMENT = CLinker.toCString("siphash24", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_sign_PRIMITIVE$SEGMENT = CLinker.toCString("ed25519", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_stream_PRIMITIVE$SEGMENT = CLinker.toCString("xsalsa20", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_pwhash_scryptsalsa208sha256_STRPREFIX$SEGMENT = CLinker.toCString("$7$", ResourceScope.newImplicitScope());
}


