// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$2 {

    static final FunctionDescriptor crypto_aead_aes256gcm_npubbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_aead_aes256gcm_npubbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_npubbytes",
        "()J",
        constants$2.crypto_aead_aes256gcm_npubbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_abytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_aead_aes256gcm_abytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_abytes",
        "()J",
        constants$2.crypto_aead_aes256gcm_abytes$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_aead_aes256gcm_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_messagebytes_max",
        "()J",
        constants$2.crypto_aead_aes256gcm_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_statebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_aead_aes256gcm_statebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_statebytes",
        "()J",
        constants$2.crypto_aead_aes256gcm_statebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_encrypt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_encrypt$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_encrypt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$2.crypto_aead_aes256gcm_encrypt$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_aes256gcm_decrypt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_aes256gcm_decrypt$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_aes256gcm_decrypt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$2.crypto_aead_aes256gcm_decrypt$FUNC, false
    );
}


