// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$45 {

    static final FunctionDescriptor crypto_pwhash_argon2i_str_needs_rehash$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_pwhash_argon2i_str_needs_rehash$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_str_needs_rehash",
        constants$45.crypto_pwhash_argon2i_str_needs_rehash$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_alg_argon2id13$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_alg_argon2id13$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_alg_argon2id13",
        constants$45.crypto_pwhash_argon2id_alg_argon2id13$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_bytes_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_bytes_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_bytes_min",
        constants$45.crypto_pwhash_argon2id_bytes_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_bytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_bytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_bytes_max",
        constants$45.crypto_pwhash_argon2id_bytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_passwd_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_passwd_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_passwd_min",
        constants$45.crypto_pwhash_argon2id_passwd_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_passwd_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2id_passwd_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2id_passwd_max",
        constants$45.crypto_pwhash_argon2id_passwd_max$FUNC, false
    );
}


