// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$83 {

    static final FunctionDescriptor crypto_stream_xchacha20_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_xchacha20_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_messagebytes_max",
        "()J",
        constants$83.crypto_stream_xchacha20_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_stream_xchacha20$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$83.crypto_stream_xchacha20$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_xor$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_stream_xchacha20_xor$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_xor",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$83.crypto_stream_xchacha20_xor$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_xor_ic$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle crypto_stream_xchacha20_xor_ic$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_xor_ic",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$83.crypto_stream_xchacha20_xor_ic$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_keygen$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_stream_xchacha20_keygen$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_keygen",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$83.crypto_stream_xchacha20_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_seedbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_seedbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_seedbytes",
        "()J",
        constants$83.crypto_box_curve25519xchacha20poly1305_seedbytes$FUNC, false
    );
}


