// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$31 {

    static final FunctionDescriptor crypto_generichash_blake2b$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle crypto_generichash_blake2b$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;J)I",
        constants$31.crypto_generichash_blake2b$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_salt_personal$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_generichash_blake2b_salt_personal$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b_salt_personal",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$31.crypto_generichash_blake2b_salt_personal$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_init$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle crypto_generichash_blake2b_init$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b_init",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$31.crypto_generichash_blake2b_init$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_init_salt_personal$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_generichash_blake2b_init_salt_personal$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b_init_salt_personal",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$31.crypto_generichash_blake2b_init_salt_personal$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_update$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle crypto_generichash_blake2b_update$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b_update",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$31.crypto_generichash_blake2b_update$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_final$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG
    );
    static final MethodHandle crypto_generichash_blake2b_final$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_generichash_blake2b_final",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$31.crypto_generichash_blake2b_final$FUNC, false
    );
}


