// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$26 {

    static final FunctionDescriptor crypto_core_hsalsa20$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_hsalsa20$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hsalsa20",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$26.crypto_core_hsalsa20$FUNC, false
    );
    static final FunctionDescriptor crypto_core_hchacha20_outputbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_hchacha20_outputbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hchacha20_outputbytes",
        "()J",
        constants$26.crypto_core_hchacha20_outputbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_hchacha20_inputbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_hchacha20_inputbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hchacha20_inputbytes",
        "()J",
        constants$26.crypto_core_hchacha20_inputbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_hchacha20_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_hchacha20_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hchacha20_keybytes",
        "()J",
        constants$26.crypto_core_hchacha20_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_hchacha20_constbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_hchacha20_constbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hchacha20_constbytes",
        "()J",
        constants$26.crypto_core_hchacha20_constbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_hchacha20$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_hchacha20$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_hchacha20",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$26.crypto_core_hchacha20$FUNC, false
    );
}


