// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$57 {

    static final FunctionDescriptor crypto_secretbox_easy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_secretbox_easy$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_easy",
        constants$57.crypto_secretbox_easy$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_open_easy$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_secretbox_open_easy$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_open_easy",
        constants$57.crypto_secretbox_open_easy$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_detached$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_secretbox_detached$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_detached",
        constants$57.crypto_secretbox_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_open_detached$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_secretbox_open_detached$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_open_detached",
        constants$57.crypto_secretbox_open_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_secretbox_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_keygen",
        constants$57.crypto_secretbox_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_zerobytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretbox_zerobytes$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_zerobytes",
        constants$57.crypto_secretbox_zerobytes$FUNC, false
    );
}


