// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$15 {

    static final FunctionDescriptor crypto_hash_sha256_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_hash_sha256_update$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256_update",
        constants$15.crypto_hash_sha256_update$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha256_final$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_hash_sha256_final$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256_final",
        constants$15.crypto_hash_sha256_final$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_hmacsha256_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_auth_hmacsha256_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha256_bytes",
        constants$15.crypto_auth_hmacsha256_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_hmacsha256_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_auth_hmacsha256_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha256_keybytes",
        constants$15.crypto_auth_hmacsha256_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_hmacsha256$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_hmacsha256$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha256",
        constants$15.crypto_auth_hmacsha256$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_hmacsha256_verify$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_hmacsha256_verify$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha256_verify",
        constants$15.crypto_auth_hmacsha256_verify$FUNC, false
    );
}


