// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$97 {

    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_saltbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_saltbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_saltbytes",
        constants$97.crypto_pwhash_scryptsalsa208sha256_saltbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_strbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_strbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_strbytes",
        constants$97.crypto_pwhash_scryptsalsa208sha256_strbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_strprefix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_strprefix$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_strprefix",
        constants$97.crypto_pwhash_scryptsalsa208sha256_strprefix$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_opslimit_min",
        constants$97.crypto_pwhash_scryptsalsa208sha256_opslimit_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_opslimit_max",
        constants$97.crypto_pwhash_scryptsalsa208sha256_opslimit_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_memlimit_min",
        constants$97.crypto_pwhash_scryptsalsa208sha256_memlimit_min$FUNC, false
    );
}


