// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$5 {

    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_messagebytes_max",
        "()J",
        constants$5.crypto_aead_chacha20poly1305_ietf_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_encrypt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_encrypt$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_encrypt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.crypto_aead_chacha20poly1305_ietf_encrypt$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_decrypt$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_decrypt$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_decrypt",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.crypto_aead_chacha20poly1305_ietf_decrypt$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_encrypt_detached$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_encrypt_detached$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_encrypt_detached",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.crypto_aead_chacha20poly1305_ietf_encrypt_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_decrypt_detached$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_decrypt_detached$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_decrypt_detached",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.crypto_aead_chacha20poly1305_ietf_decrypt_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_chacha20poly1305_ietf_keygen$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_aead_chacha20poly1305_ietf_keygen$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_chacha20poly1305_ietf_keygen",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$5.crypto_aead_chacha20poly1305_ietf_keygen$FUNC, false
    );
}


