// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$36 {

    static final FunctionDescriptor crypto_kdf_contextbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_contextbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_contextbytes",
        constants$36.crypto_kdf_contextbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kdf_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_keybytes",
        constants$36.crypto_kdf_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_primitive$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_kdf_primitive$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_primitive",
        constants$36.crypto_kdf_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_derive_from_key$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_kdf_derive_from_key$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_derive_from_key",
        constants$36.crypto_kdf_derive_from_key$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_kdf_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_kdf_keygen",
        constants$36.crypto_kdf_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_kx_publickeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_kx_publickeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_kx_publickeybytes",
        constants$36.crypto_kx_publickeybytes$FUNC, false
    );
}


