// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$74 {

    static final FunctionDescriptor crypto_verify_32_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_verify_32_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_verify_32_bytes",
        constants$74.crypto_verify_32_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_verify_32$MH = RuntimeHelper.downcallHandle(
        "crypto_verify_32",
        constants$74.crypto_verify_32$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_64_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_verify_64_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_verify_64_bytes",
        constants$74.crypto_verify_64_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_verify_64$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_verify_64$MH = RuntimeHelper.downcallHandle(
        "crypto_verify_64",
        constants$74.crypto_verify_64$FUNC, false
    );
    static final FunctionDescriptor randombytes_seedbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle randombytes_seedbytes$MH = RuntimeHelper.downcallHandle(
        "randombytes_seedbytes",
        constants$74.randombytes_seedbytes$FUNC, false
    );
    static final FunctionDescriptor randombytes_buf$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle randombytes_buf$MH = RuntimeHelper.downcallHandle(
        "randombytes_buf",
        constants$74.randombytes_buf$FUNC, false
    );
}


