// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$83 {

    static final FunctionDescriptor crypto_stream_xchacha20_messagebytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_stream_xchacha20_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xchacha20_messagebytes_max",
        constants$83.crypto_stream_xchacha20_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xchacha20$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xchacha20",
        constants$83.crypto_stream_xchacha20$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_xor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xchacha20_xor$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xchacha20_xor",
        constants$83.crypto_stream_xchacha20_xor$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_xor_ic$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xchacha20_xor_ic$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xchacha20_xor_ic",
        constants$83.crypto_stream_xchacha20_xor_ic$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xchacha20_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xchacha20_keygen",
        constants$83.crypto_stream_xchacha20_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_seedbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_seedbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_seedbytes",
        constants$83.crypto_box_curve25519xchacha20poly1305_seedbytes$FUNC, false
    );
}


