// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$76 {

    static final FunctionDescriptor randombytes_implementation_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle randombytes_implementation_name$MH = RuntimeHelper.downcallHandle(
        "randombytes_implementation_name",
        constants$76.randombytes_implementation_name$FUNC, false
    );
    static final FunctionDescriptor randombytes$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle randombytes$MH = RuntimeHelper.downcallHandle(
        "randombytes",
        constants$76.randombytes$FUNC, false
    );
    static final  GroupLayout randombytes_internal_implementation$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("implementation_name"),
        Constants$root.C_POINTER$LAYOUT.withName("random"),
        Constants$root.C_POINTER$LAYOUT.withName("stir"),
        Constants$root.C_POINTER$LAYOUT.withName("uniform"),
        Constants$root.C_POINTER$LAYOUT.withName("buf"),
        Constants$root.C_POINTER$LAYOUT.withName("close")
    ).withName("randombytes_implementation");
    static final MemorySegment randombytes_internal_implementation$SEGMENT = RuntimeHelper.lookupGlobalVariable("randombytes_internal_implementation", constants$76.randombytes_internal_implementation$LAYOUT);
    static final  GroupLayout randombytes_sysrandom_implementation$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("implementation_name"),
        Constants$root.C_POINTER$LAYOUT.withName("random"),
        Constants$root.C_POINTER$LAYOUT.withName("stir"),
        Constants$root.C_POINTER$LAYOUT.withName("uniform"),
        Constants$root.C_POINTER$LAYOUT.withName("buf"),
        Constants$root.C_POINTER$LAYOUT.withName("close")
    ).withName("randombytes_implementation");
    static final MemorySegment randombytes_sysrandom_implementation$SEGMENT = RuntimeHelper.lookupGlobalVariable("randombytes_sysrandom_implementation", constants$76.randombytes_sysrandom_implementation$LAYOUT);
    static final FunctionDescriptor sodium_runtime_has_neon$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_runtime_has_neon$MH = RuntimeHelper.downcallHandle(
        "sodium_runtime_has_neon",
        constants$76.sodium_runtime_has_neon$FUNC, false
    );
    static final FunctionDescriptor sodium_runtime_has_sse2$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle sodium_runtime_has_sse2$MH = RuntimeHelper.downcallHandle(
        "sodium_runtime_has_sse2",
        constants$76.sodium_runtime_has_sse2$FUNC, false
    );
}


