// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$65 {

    static final FunctionDescriptor crypto_shorthash_keygen$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_shorthash_keygen$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_keygen",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$65.crypto_shorthash_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519ph_statebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_sign_ed25519ph_statebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_ed25519ph_statebytes",
        "()J",
        constants$65.crypto_sign_ed25519ph_statebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_bytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_sign_ed25519_bytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_ed25519_bytes",
        "()J",
        constants$65.crypto_sign_ed25519_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_seedbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_sign_ed25519_seedbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_ed25519_seedbytes",
        "()J",
        constants$65.crypto_sign_ed25519_seedbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_publickeybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_sign_ed25519_publickeybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_ed25519_publickeybytes",
        "()J",
        constants$65.crypto_sign_ed25519_publickeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_secretkeybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_sign_ed25519_secretkeybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_ed25519_secretkeybytes",
        "()J",
        constants$65.crypto_sign_ed25519_secretkeybytes$FUNC, false
    );
}


