// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$13 {

    static final FunctionDescriptor crypto_auth_hmacsha512256_final$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_hmacsha512256_final$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha512256_final",
        constants$13.crypto_auth_hmacsha512256_final$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_hmacsha512256_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_hmacsha512256_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_hmacsha512256_keygen",
        constants$13.crypto_auth_hmacsha512256_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_auth_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_bytes",
        constants$13.crypto_auth_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_auth_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_keybytes",
        constants$13.crypto_auth_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_primitive$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_auth_primitive$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_primitive",
        constants$13.crypto_auth_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_auth$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth$MH = RuntimeHelper.downcallHandle(
        "crypto_auth",
        constants$13.crypto_auth$FUNC, false
    );
}


