// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$67 {

    static final FunctionDescriptor crypto_sign_ed25519_seed_keypair$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519_seed_keypair$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519_seed_keypair",
        constants$67.crypto_sign_ed25519_seed_keypair$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_pk_to_curve25519$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519_pk_to_curve25519$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519_pk_to_curve25519",
        constants$67.crypto_sign_ed25519_pk_to_curve25519$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_sk_to_curve25519$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519_sk_to_curve25519$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519_sk_to_curve25519",
        constants$67.crypto_sign_ed25519_sk_to_curve25519$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_sk_to_seed$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519_sk_to_seed$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519_sk_to_seed",
        constants$67.crypto_sign_ed25519_sk_to_seed$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519_sk_to_pk$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519_sk_to_pk$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519_sk_to_pk",
        constants$67.crypto_sign_ed25519_sk_to_pk$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_ed25519ph_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_ed25519ph_init$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_ed25519ph_init",
        constants$67.crypto_sign_ed25519ph_init$FUNC, false
    );
}


