// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$20 {

    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xsalsa20poly1305",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$20.crypto_box_curve25519xsalsa20poly1305$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_open$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_open$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xsalsa20poly1305_open",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$20.crypto_box_curve25519xsalsa20poly1305_open$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xsalsa20poly1305_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$20.crypto_box_curve25519xsalsa20poly1305_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_open_afternm$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_open_afternm$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xsalsa20poly1305_open_afternm",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$20.crypto_box_curve25519xsalsa20poly1305_open_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_seedbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_seedbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_seedbytes",
        "()J",
        constants$20.crypto_box_seedbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_publickeybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_publickeybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_publickeybytes",
        "()J",
        constants$20.crypto_box_publickeybytes$FUNC, false
    );
}


