// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$24 {

    static final FunctionDescriptor crypto_box_seal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_seal$MH = RuntimeHelper.downcallHandle(
        "crypto_box_seal",
        constants$24.crypto_box_seal$FUNC, false
    );
    static final FunctionDescriptor crypto_box_seal_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_seal_open$MH = RuntimeHelper.downcallHandle(
        "crypto_box_seal_open",
        constants$24.crypto_box_seal_open$FUNC, false
    );
    static final FunctionDescriptor crypto_box_zerobytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_zerobytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_zerobytes",
        constants$24.crypto_box_zerobytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_boxzerobytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_boxzerobytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_boxzerobytes",
        constants$24.crypto_box_boxzerobytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box$MH = RuntimeHelper.downcallHandle(
        "crypto_box",
        constants$24.crypto_box$FUNC, false
    );
    static final FunctionDescriptor crypto_box_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_open$MH = RuntimeHelper.downcallHandle(
        "crypto_box_open",
        constants$24.crypto_box_open$FUNC, false
    );
}


