// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$41 {

    static final FunctionDescriptor crypto_onetimeauth_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_update$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_update",
        constants$41.crypto_onetimeauth_update$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_final$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_final$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_final",
        constants$41.crypto_onetimeauth_final$FUNC, false
    );
    static final FunctionDescriptor crypto_onetimeauth_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_onetimeauth_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_onetimeauth_keygen",
        constants$41.crypto_onetimeauth_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_alg_argon2i13$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_alg_argon2i13$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_alg_argon2i13",
        constants$41.crypto_pwhash_argon2i_alg_argon2i13$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_bytes_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_bytes_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_bytes_min",
        constants$41.crypto_pwhash_argon2i_bytes_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_bytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_bytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_bytes_max",
        constants$41.crypto_pwhash_argon2i_bytes_max$FUNC, false
    );
}


