// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$14 {

    static final FunctionDescriptor crypto_auth_verify$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_verify$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_verify",
        constants$14.crypto_auth_verify$FUNC, false
    );
    static final FunctionDescriptor crypto_auth_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_auth_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_auth_keygen",
        constants$14.crypto_auth_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha256_statebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_hash_sha256_statebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256_statebytes",
        constants$14.crypto_hash_sha256_statebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha256_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_hash_sha256_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256_bytes",
        constants$14.crypto_hash_sha256_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha256$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_hash_sha256$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256",
        constants$14.crypto_hash_sha256$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha256_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_hash_sha256_init$MH = RuntimeHelper.downcallHandle(
        "crypto_hash_sha256_init",
        constants$14.crypto_hash_sha256_init$FUNC, false
    );
}


