// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$98 {

    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_memlimit_max",
        "()J",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_opslimit_interactive",
        "()J",
        constants$98.crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_memlimit_interactive",
        "()J",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive",
        "()J",
        constants$98.crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive",
        "()J",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_LONG
    );
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$98.crypto_pwhash_scryptsalsa208sha256$FUNC, false
    );
}


