// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$42 {

    static final FunctionDescriptor crypto_pwhash_argon2i_passwd_min$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2i_passwd_min$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_passwd_min",
        "()J",
        constants$42.crypto_pwhash_argon2i_passwd_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_passwd_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2i_passwd_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_passwd_max",
        "()J",
        constants$42.crypto_pwhash_argon2i_passwd_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_saltbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2i_saltbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_saltbytes",
        "()J",
        constants$42.crypto_pwhash_argon2i_saltbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_strbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2i_strbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_strbytes",
        "()J",
        constants$42.crypto_pwhash_argon2i_strbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_strprefix$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle crypto_pwhash_argon2i_strprefix$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_strprefix",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$42.crypto_pwhash_argon2i_strprefix$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_opslimit_min$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2i_opslimit_min$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2i_opslimit_min",
        "()J",
        constants$42.crypto_pwhash_argon2i_opslimit_min$FUNC, false
    );
}


