// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$20 {

    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xsalsa20poly1305",
        constants$20.crypto_box_curve25519xsalsa20poly1305$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_open$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xsalsa20poly1305_open",
        constants$20.crypto_box_curve25519xsalsa20poly1305_open$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xsalsa20poly1305_afternm",
        constants$20.crypto_box_curve25519xsalsa20poly1305_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xsalsa20poly1305_open_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xsalsa20poly1305_open_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xsalsa20poly1305_open_afternm",
        constants$20.crypto_box_curve25519xsalsa20poly1305_open_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_seedbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_seedbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_seedbytes",
        constants$20.crypto_box_seedbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_publickeybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_publickeybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_publickeybytes",
        constants$20.crypto_box_publickeybytes$FUNC, false
    );
}


