// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$93 {

    static final FunctionDescriptor crypto_core_ristretto255_scalar_mul$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_core_ristretto255_scalar_mul$MH = RuntimeHelper.downcallHandle(
        "crypto_core_ristretto255_scalar_mul",
        constants$93.crypto_core_ristretto255_scalar_mul$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ristretto255_scalar_reduce$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_core_ristretto255_scalar_reduce$MH = RuntimeHelper.downcallHandle(
        "crypto_core_ristretto255_scalar_reduce",
        constants$93.crypto_core_ristretto255_scalar_reduce$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_ed25519_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_scalarmult_ed25519_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_ed25519_bytes",
        constants$93.crypto_scalarmult_ed25519_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_ed25519_scalarbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_scalarmult_ed25519_scalarbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_ed25519_scalarbytes",
        constants$93.crypto_scalarmult_ed25519_scalarbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_ed25519$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_scalarmult_ed25519$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_ed25519",
        constants$93.crypto_scalarmult_ed25519$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_ed25519_noclamp$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_scalarmult_ed25519_noclamp$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_ed25519_noclamp",
        constants$93.crypto_scalarmult_ed25519_noclamp$FUNC, false
    );
}


