// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$52 {

    static final FunctionDescriptor crypto_pwhash_memlimit_sensitive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_memlimit_sensitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_memlimit_sensitive",
        "()J",
        constants$52.crypto_pwhash_memlimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_LONG_LONG,
        C_LONG,
        C_INT
    );
    static final MethodHandle crypto_pwhash$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash",
        "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;JJI)I",
        constants$52.crypto_pwhash$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_str$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_LONG_LONG,
        C_LONG
    );
    static final MethodHandle crypto_pwhash_str$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_str",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJJ)I",
        constants$52.crypto_pwhash_str$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_str_alg$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_LONG_LONG,
        C_LONG,
        C_INT
    );
    static final MethodHandle crypto_pwhash_str_alg$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_str_alg",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJJI)I",
        constants$52.crypto_pwhash_str_alg$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_str_verify$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle crypto_pwhash_str_verify$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_str_verify",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$52.crypto_pwhash_str_verify$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_str_needs_rehash$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG_LONG,
        C_LONG
    );
    static final MethodHandle crypto_pwhash_str_needs_rehash$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_str_needs_rehash",
        "(Ljdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$52.crypto_pwhash_str_needs_rehash$FUNC, false
    );
}


