// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$81 {

    static final FunctionDescriptor sodium_munlock$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sodium_munlock$MH = RuntimeHelper.downcallHandle(
        "sodium_munlock",
        constants$81.sodium_munlock$FUNC, false
    );
    static final FunctionDescriptor sodium_malloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sodium_malloc$MH = RuntimeHelper.downcallHandle(
        "sodium_malloc",
        constants$81.sodium_malloc$FUNC, false
    );
    static final FunctionDescriptor sodium_allocarray$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle sodium_allocarray$MH = RuntimeHelper.downcallHandle(
        "sodium_allocarray",
        constants$81.sodium_allocarray$FUNC, false
    );
    static final FunctionDescriptor sodium_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sodium_free$MH = RuntimeHelper.downcallHandle(
        "sodium_free",
        constants$81.sodium_free$FUNC, false
    );
    static final FunctionDescriptor sodium_mprotect_noaccess$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sodium_mprotect_noaccess$MH = RuntimeHelper.downcallHandle(
        "sodium_mprotect_noaccess",
        constants$81.sodium_mprotect_noaccess$FUNC, false
    );
    static final FunctionDescriptor sodium_mprotect_readonly$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle sodium_mprotect_readonly$MH = RuntimeHelper.downcallHandle(
        "sodium_mprotect_readonly",
        constants$81.sodium_mprotect_readonly$FUNC, false
    );
}


