// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$54 {

    static final FunctionDescriptor crypto_scalarmult_scalarbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_scalarmult_scalarbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_scalarbytes",
        constants$54.crypto_scalarmult_scalarbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_primitive$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_scalarmult_primitive$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_primitive",
        constants$54.crypto_scalarmult_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult_base$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_scalarmult_base$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult_base",
        constants$54.crypto_scalarmult_base$FUNC, false
    );
    static final FunctionDescriptor crypto_scalarmult$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_scalarmult$MH = RuntimeHelper.downcallHandle(
        "crypto_scalarmult",
        constants$54.crypto_scalarmult$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_xsalsa20poly1305_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretbox_xsalsa20poly1305_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_xsalsa20poly1305_keybytes",
        constants$54.crypto_secretbox_xsalsa20poly1305_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_xsalsa20poly1305_noncebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_secretbox_xsalsa20poly1305_noncebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_secretbox_xsalsa20poly1305_noncebytes",
        constants$54.crypto_secretbox_xsalsa20poly1305_noncebytes$FUNC, false
    );
}


