// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$71 {

    static final FunctionDescriptor crypto_sign_final_create$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_sign_final_create$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_final_create",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$71.crypto_sign_final_create$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_final_verify$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_sign_final_verify$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_sign_final_verify",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$71.crypto_sign_final_verify$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_keybytes",
        "()J",
        constants$71.crypto_stream_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_noncebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_noncebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_noncebytes",
        "()J",
        constants$71.crypto_stream_noncebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_messagebytes_max",
        "()J",
        constants$71.crypto_stream_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_primitive$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle crypto_stream_primitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_primitive",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$71.crypto_stream_primitive$FUNC, false
    );
}


