// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$59 {

    static final FunctionDescriptor crypto_stream_chacha20$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_chacha20$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20",
        constants$59.crypto_stream_chacha20$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_xor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_chacha20_xor$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20_xor",
        constants$59.crypto_stream_chacha20_xor$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_xor_ic$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_chacha20_xor_ic$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20_xor_ic",
        constants$59.crypto_stream_chacha20_xor_ic$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_chacha20_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20_keygen",
        constants$59.crypto_stream_chacha20_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_stream_chacha20_ietf_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20_ietf_keybytes",
        constants$59.crypto_stream_chacha20_ietf_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_chacha20_ietf_noncebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_stream_chacha20_ietf_noncebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_chacha20_ietf_noncebytes",
        constants$59.crypto_stream_chacha20_ietf_noncebytes$FUNC, false
    );
}


