// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$70 {

    static final FunctionDescriptor crypto_sign$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign$MH = RuntimeHelper.downcallHandle(
        "crypto_sign",
        constants$70.crypto_sign$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_open$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_open",
        constants$70.crypto_sign_open$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_detached$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_detached$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_detached",
        constants$70.crypto_sign_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_verify_detached$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_verify_detached$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_verify_detached",
        constants$70.crypto_sign_verify_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_sign_init$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_init",
        constants$70.crypto_sign_init$FUNC, false
    );
    static final FunctionDescriptor crypto_sign_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_sign_update$MH = RuntimeHelper.downcallHandle(
        "crypto_sign_update",
        constants$70.crypto_sign_update$FUNC, false
    );
}


