// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$31 {

    static final FunctionDescriptor crypto_generichash_blake2b$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b",
        constants$31.crypto_generichash_blake2b$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_salt_personal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b_salt_personal$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_salt_personal",
        constants$31.crypto_generichash_blake2b_salt_personal$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_init$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b_init$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_init",
        constants$31.crypto_generichash_blake2b_init$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_init_salt_personal$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b_init_salt_personal$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_init_salt_personal",
        constants$31.crypto_generichash_blake2b_init_salt_personal$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_update$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b_update$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_update",
        constants$31.crypto_generichash_blake2b_update$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_final$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_generichash_blake2b_final$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_final",
        constants$31.crypto_generichash_blake2b_final$FUNC, false
    );
}


