// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$98 {

    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_memlimit_max",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_opslimit_interactive",
        constants$98.crypto_pwhash_scryptsalsa208sha256_opslimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_memlimit_interactive",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive",
        constants$98.crypto_pwhash_scryptsalsa208sha256_opslimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive",
        constants$98.crypto_pwhash_scryptsalsa208sha256_memlimit_sensitive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_scryptsalsa208sha256",
        constants$98.crypto_pwhash_scryptsalsa208sha256$FUNC, false
    );
}


