// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$35 {

    static final FunctionDescriptor crypto_kdf_blake2b_bytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_kdf_blake2b_bytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_blake2b_bytes_max",
        "()J",
        constants$35.crypto_kdf_blake2b_bytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_contextbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_kdf_blake2b_contextbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_blake2b_contextbytes",
        "()J",
        constants$35.crypto_kdf_blake2b_contextbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_kdf_blake2b_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_blake2b_keybytes",
        "()J",
        constants$35.crypto_kdf_blake2b_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_blake2b_derive_from_key$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_LONG,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_kdf_blake2b_derive_from_key$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_blake2b_derive_from_key",
        "(Ljdk/incubator/foreign/MemoryAddress;JJLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$35.crypto_kdf_blake2b_derive_from_key$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_bytes_min$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_kdf_bytes_min$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_bytes_min",
        "()J",
        constants$35.crypto_kdf_bytes_min$FUNC, false
    );
    static final FunctionDescriptor crypto_kdf_bytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_kdf_bytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_kdf_bytes_max",
        "()J",
        constants$35.crypto_kdf_bytes_max$FUNC, false
    );
}


