// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$64 {

    static final FunctionDescriptor crypto_shorthash_siphashx24_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_shorthash_siphashx24_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_siphashx24_keybytes",
        "()J",
        constants$64.crypto_shorthash_siphashx24_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_shorthash_siphashx24$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle crypto_shorthash_siphashx24$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_siphashx24",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$64.crypto_shorthash_siphashx24$FUNC, false
    );
    static final FunctionDescriptor crypto_shorthash_bytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_shorthash_bytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_bytes",
        "()J",
        constants$64.crypto_shorthash_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_shorthash_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_shorthash_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_keybytes",
        "()J",
        constants$64.crypto_shorthash_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_shorthash_primitive$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle crypto_shorthash_primitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash_primitive",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$64.crypto_shorthash_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_shorthash$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER
    );
    static final MethodHandle crypto_shorthash$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_shorthash",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I",
        constants$64.crypto_shorthash$FUNC, false
    );
}


