// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$102 {

    static final MemorySegment crypto_box_PRIMITIVE$SEGMENT = CLinker.toCString("curve25519xsalsa20poly1305", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_generichash_PRIMITIVE$SEGMENT = CLinker.toCString("blake2b", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_hash_PRIMITIVE$SEGMENT = CLinker.toCString("sha512", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_kdf_PRIMITIVE$SEGMENT = CLinker.toCString("blake2b", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_kx_PRIMITIVE$SEGMENT = CLinker.toCString("x25519blake2b", ResourceScope.newImplicitScope());
    static final MemorySegment crypto_onetimeauth_PRIMITIVE$SEGMENT = CLinker.toCString("poly1305", ResourceScope.newImplicitScope());
}


