// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$27 {

    static final FunctionDescriptor crypto_core_salsa20_outputbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_salsa20_outputbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa20_outputbytes",
        "()J",
        constants$27.crypto_core_salsa20_outputbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa20_inputbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_salsa20_inputbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa20_inputbytes",
        "()J",
        constants$27.crypto_core_salsa20_inputbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa20_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_salsa20_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa20_keybytes",
        "()J",
        constants$27.crypto_core_salsa20_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa20_constbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_salsa20_constbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa20_constbytes",
        "()J",
        constants$27.crypto_core_salsa20_constbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa20$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_salsa20$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa20",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$27.crypto_core_salsa20$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa2012_outputbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_salsa2012_outputbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_salsa2012_outputbytes",
        "()J",
        constants$27.crypto_core_salsa2012_outputbytes$FUNC, false
    );
}


