// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$17 {

    static final FunctionDescriptor crypto_stream_xsalsa20_noncebytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_stream_xsalsa20_noncebytes$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20_noncebytes",
        constants$17.crypto_stream_xsalsa20_noncebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xsalsa20_messagebytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_stream_xsalsa20_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20_messagebytes_max",
        constants$17.crypto_stream_xsalsa20_messagebytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xsalsa20$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xsalsa20$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20",
        constants$17.crypto_stream_xsalsa20$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xsalsa20_xor$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xsalsa20_xor$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20_xor",
        constants$17.crypto_stream_xsalsa20_xor$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xsalsa20_xor_ic$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xsalsa20_xor_ic$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20_xor_ic",
        constants$17.crypto_stream_xsalsa20_xor_ic$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xsalsa20_keygen$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_stream_xsalsa20_keygen$MH = RuntimeHelper.downcallHandle(
        "crypto_stream_xsalsa20_keygen",
        constants$17.crypto_stream_xsalsa20_keygen$FUNC, false
    );
}


