// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$75 {

    static final FunctionDescriptor randombytes_buf_deterministic$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle randombytes_buf_deterministic$MH = RuntimeHelper.downcallHandle(
        "randombytes_buf_deterministic",
        constants$75.randombytes_buf_deterministic$FUNC, false
    );
    static final FunctionDescriptor randombytes_random$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle randombytes_random$MH = RuntimeHelper.downcallHandle(
        "randombytes_random",
        constants$75.randombytes_random$FUNC, false
    );
    static final FunctionDescriptor randombytes_uniform$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle randombytes_uniform$MH = RuntimeHelper.downcallHandle(
        "randombytes_uniform",
        constants$75.randombytes_uniform$FUNC, false
    );
    static final FunctionDescriptor randombytes_stir$FUNC = FunctionDescriptor.ofVoid();
    static final MethodHandle randombytes_stir$MH = RuntimeHelper.downcallHandle(
        "randombytes_stir",
        constants$75.randombytes_stir$FUNC, false
    );
    static final FunctionDescriptor randombytes_close$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT);
    static final MethodHandle randombytes_close$MH = RuntimeHelper.downcallHandle(
        "randombytes_close",
        constants$75.randombytes_close$FUNC, false
    );
    static final FunctionDescriptor randombytes_set_implementation$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle randombytes_set_implementation$MH = RuntimeHelper.downcallHandle(
        "randombytes_set_implementation",
        constants$75.randombytes_set_implementation$FUNC, false
    );
}


