// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$23 {

    static final FunctionDescriptor crypto_box_beforenm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_beforenm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_beforenm",
        constants$23.crypto_box_beforenm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_easy_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_easy_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_easy_afternm",
        constants$23.crypto_box_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_open_easy_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_open_easy_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_open_easy_afternm",
        constants$23.crypto_box_open_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_detached_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_detached_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_detached_afternm",
        constants$23.crypto_box_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_open_detached_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_open_detached_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_open_detached_afternm",
        constants$23.crypto_box_open_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_sealbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_sealbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_sealbytes",
        constants$23.crypto_box_sealbytes$FUNC, false
    );
}


