// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$82 {

    static final FunctionDescriptor sodium_mprotect_readwrite$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle sodium_mprotect_readwrite$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "sodium_mprotect_readwrite",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$82.sodium_mprotect_readwrite$FUNC, false
    );
    static final FunctionDescriptor sodium_pad$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG,
        C_LONG
    );
    static final MethodHandle sodium_pad$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "sodium_pad",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJJ)I",
        constants$82.sodium_pad$FUNC, false
    );
    static final FunctionDescriptor sodium_unpad$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG,
        C_LONG
    );
    static final MethodHandle sodium_unpad$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "sodium_unpad",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JJ)I",
        constants$82.sodium_unpad$FUNC, false
    );
    static final FunctionDescriptor _sodium_alloc_init$FUNC = FunctionDescriptor.of(C_INT);
    static final MethodHandle _sodium_alloc_init$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "_sodium_alloc_init",
        "()I",
        constants$82._sodium_alloc_init$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_xchacha20_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_keybytes",
        "()J",
        constants$82.crypto_stream_xchacha20_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_stream_xchacha20_noncebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_stream_xchacha20_noncebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_stream_xchacha20_noncebytes",
        "()J",
        constants$82.crypto_stream_xchacha20_noncebytes$FUNC, false
    );
}


