// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$56 {

    static final FunctionDescriptor crypto_secretbox_xsalsa20poly1305_zerobytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretbox_xsalsa20poly1305_zerobytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_xsalsa20poly1305_zerobytes",
        "()J",
        constants$56.crypto_secretbox_xsalsa20poly1305_zerobytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_keybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretbox_keybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_keybytes",
        "()J",
        constants$56.crypto_secretbox_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_noncebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretbox_noncebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_noncebytes",
        "()J",
        constants$56.crypto_secretbox_noncebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_macbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretbox_macbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_macbytes",
        "()J",
        constants$56.crypto_secretbox_macbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_primitive$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle crypto_secretbox_primitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_primitive",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$56.crypto_secretbox_primitive$FUNC, false
    );
    static final FunctionDescriptor crypto_secretbox_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_secretbox_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_secretbox_messagebytes_max",
        "()J",
        constants$56.crypto_secretbox_messagebytes_max$FUNC, false
    );
}


