// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$84 {

    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_publickeybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_publickeybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_publickeybytes",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_publickeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_secretkeybytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_secretkeybytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_secretkeybytes",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_secretkeybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_beforenmbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_beforenmbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_beforenmbytes",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_beforenmbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_noncebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_noncebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_noncebytes",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_noncebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_macbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_macbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_macbytes",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_macbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_messagebytes_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_messagebytes_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_box_curve25519xchacha20poly1305_messagebytes_max",
        "()J",
        constants$84.crypto_box_curve25519xchacha20poly1305_messagebytes_max$FUNC, false
    );
}


