// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$86 {

    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_beforenm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_beforenm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_beforenm",
        constants$86.crypto_box_curve25519xchacha20poly1305_beforenm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_easy_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_easy_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_easy_afternm",
        constants$86.crypto_box_curve25519xchacha20poly1305_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_open_easy_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_open_easy_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_open_easy_afternm",
        constants$86.crypto_box_curve25519xchacha20poly1305_open_easy_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_detached_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_detached_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_detached_afternm",
        constants$86.crypto_box_curve25519xchacha20poly1305_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_open_detached_afternm$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_open_detached_afternm$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_open_detached_afternm",
        constants$86.crypto_box_curve25519xchacha20poly1305_open_detached_afternm$FUNC, false
    );
    static final FunctionDescriptor crypto_box_curve25519xchacha20poly1305_sealbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_box_curve25519xchacha20poly1305_sealbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_box_curve25519xchacha20poly1305_sealbytes",
        constants$86.crypto_box_curve25519xchacha20poly1305_sealbytes$FUNC, false
    );
}


