// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$47 {

    static final FunctionDescriptor crypto_pwhash_argon2id_memlimit_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_memlimit_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_memlimit_max",
        "()J",
        constants$47.crypto_pwhash_argon2id_memlimit_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_opslimit_interactive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_opslimit_interactive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_opslimit_interactive",
        "()J",
        constants$47.crypto_pwhash_argon2id_opslimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_memlimit_interactive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_memlimit_interactive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_memlimit_interactive",
        "()J",
        constants$47.crypto_pwhash_argon2id_memlimit_interactive$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_opslimit_moderate$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_opslimit_moderate$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_opslimit_moderate",
        "()J",
        constants$47.crypto_pwhash_argon2id_opslimit_moderate$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_memlimit_moderate$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_memlimit_moderate$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_memlimit_moderate",
        "()J",
        constants$47.crypto_pwhash_argon2id_memlimit_moderate$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2id_opslimit_sensitive$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_argon2id_opslimit_sensitive$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_argon2id_opslimit_sensitive",
        "()J",
        constants$47.crypto_pwhash_argon2id_opslimit_sensitive$FUNC, false
    );
}


