// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$42 {

    static final FunctionDescriptor crypto_pwhash_argon2i_passwd_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_passwd_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_passwd_min",
        constants$42.crypto_pwhash_argon2i_passwd_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_passwd_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_passwd_max$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_passwd_max",
        constants$42.crypto_pwhash_argon2i_passwd_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_saltbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_saltbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_saltbytes",
        constants$42.crypto_pwhash_argon2i_saltbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_strbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_strbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_strbytes",
        constants$42.crypto_pwhash_argon2i_strbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_strprefix$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_strprefix$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_strprefix",
        constants$42.crypto_pwhash_argon2i_strprefix$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_argon2i_opslimit_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_pwhash_argon2i_opslimit_min$MH = RuntimeHelper.downcallHandle(
        "crypto_pwhash_argon2i_opslimit_min",
        constants$42.crypto_pwhash_argon2i_opslimit_min$FUNC, false
    );
}


