// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$88 {

    static final FunctionDescriptor crypto_core_ed25519_nonreducedscalarbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_core_ed25519_nonreducedscalarbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_nonreducedscalarbytes",
        "()J",
        constants$88.crypto_core_ed25519_nonreducedscalarbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ed25519_is_valid_point$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle crypto_core_ed25519_is_valid_point$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_is_valid_point",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$88.crypto_core_ed25519_is_valid_point$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ed25519_add$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ed25519_add$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_add",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$88.crypto_core_ed25519_add$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ed25519_sub$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ed25519_sub$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_sub",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$88.crypto_core_ed25519_sub$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ed25519_from_uniform$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ed25519_from_uniform$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_from_uniform",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$88.crypto_core_ed25519_from_uniform$FUNC, false
    );
    static final FunctionDescriptor crypto_core_ed25519_from_hash$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_core_ed25519_from_hash$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_core_ed25519_from_hash",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$88.crypto_core_ed25519_from_hash$FUNC, false
    );
}


