// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$9 {

    static final FunctionDescriptor crypto_aead_xchacha20poly1305_ietf_decrypt_detached$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle crypto_aead_xchacha20poly1305_ietf_decrypt_detached$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_xchacha20poly1305_ietf_decrypt_detached",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.crypto_aead_xchacha20poly1305_ietf_decrypt_detached$FUNC, false
    );
    static final FunctionDescriptor crypto_aead_xchacha20poly1305_ietf_keygen$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle crypto_aead_xchacha20poly1305_ietf_keygen$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_aead_xchacha20poly1305_ietf_keygen",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$9.crypto_aead_xchacha20poly1305_ietf_keygen$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha512_statebytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_hash_sha512_statebytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_hash_sha512_statebytes",
        "()J",
        constants$9.crypto_hash_sha512_statebytes$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha512_bytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_hash_sha512_bytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_hash_sha512_bytes",
        "()J",
        constants$9.crypto_hash_sha512_bytes$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha512$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_LONG_LONG
    );
    static final MethodHandle crypto_hash_sha512$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_hash_sha512",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;J)I",
        constants$9.crypto_hash_sha512$FUNC, false
    );
    static final FunctionDescriptor crypto_hash_sha512_init$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle crypto_hash_sha512_init$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_hash_sha512_init",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$9.crypto_hash_sha512_init$FUNC, false
    );
}


