// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$29 {

    static final FunctionDescriptor crypto_core_salsa208_keybytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_core_salsa208_keybytes$MH = RuntimeHelper.downcallHandle(
        "crypto_core_salsa208_keybytes",
        constants$29.crypto_core_salsa208_keybytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa208_constbytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_core_salsa208_constbytes$MH = RuntimeHelper.downcallHandle(
        "crypto_core_salsa208_constbytes",
        constants$29.crypto_core_salsa208_constbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_core_salsa208$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle crypto_core_salsa208$MH = RuntimeHelper.downcallHandle(
        "crypto_core_salsa208",
        constants$29.crypto_core_salsa208$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_bytes_min$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_generichash_blake2b_bytes_min$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_bytes_min",
        constants$29.crypto_generichash_blake2b_bytes_min$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_bytes_max$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_generichash_blake2b_bytes_max$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_bytes_max",
        constants$29.crypto_generichash_blake2b_bytes_max$FUNC, false
    );
    static final FunctionDescriptor crypto_generichash_blake2b_bytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
    static final MethodHandle crypto_generichash_blake2b_bytes$MH = RuntimeHelper.downcallHandle(
        "crypto_generichash_blake2b_bytes",
        constants$29.crypto_generichash_blake2b_bytes$FUNC, false
    );
}


