// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$97 {

    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_saltbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_saltbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_saltbytes",
        "()J",
        constants$97.crypto_pwhash_scryptsalsa208sha256_saltbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_strbytes$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_strbytes$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_strbytes",
        "()J",
        constants$97.crypto_pwhash_scryptsalsa208sha256_strbytes$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_strprefix$FUNC = FunctionDescriptor.of(C_POINTER);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_strprefix$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_strprefix",
        "()Ljdk/incubator/foreign/MemoryAddress;",
        constants$97.crypto_pwhash_scryptsalsa208sha256_strprefix$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_min$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_min$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_opslimit_min",
        "()J",
        constants$97.crypto_pwhash_scryptsalsa208sha256_opslimit_min$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_opslimit_max$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_opslimit_max$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_opslimit_max",
        "()J",
        constants$97.crypto_pwhash_scryptsalsa208sha256_opslimit_max$FUNC, false
    );
    static final FunctionDescriptor crypto_pwhash_scryptsalsa208sha256_memlimit_min$FUNC = FunctionDescriptor.of(C_LONG);
    static final MethodHandle crypto_pwhash_scryptsalsa208sha256_memlimit_min$MH = RuntimeHelper.downcallHandle(
        sodium_h.LIBRARIES, "crypto_pwhash_scryptsalsa208sha256_memlimit_min",
        "()J",
        constants$97.crypto_pwhash_scryptsalsa208sha256_memlimit_min$FUNC, false
    );
}


