// Generated by jextract

package com.github.bric3.libsodium;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
public interface sodium_set_misuse_handler$handler {

    void apply();
    static MemoryAddress allocate(sodium_set_misuse_handler$handler fi) {
        return RuntimeHelper.upcallStub(sodium_set_misuse_handler$handler.class, fi, constants$0.sodium_set_misuse_handler$handler$FUNC, "()V");
    }
    static MemoryAddress allocate(sodium_set_misuse_handler$handler fi, ResourceScope scope) {
        return RuntimeHelper.upcallStub(sodium_set_misuse_handler$handler.class, fi, constants$0.sodium_set_misuse_handler$handler$FUNC, "()V", scope);
    }
    static sodium_set_misuse_handler$handler ofAddress(MemoryAddress addr) {
        return () -> {
            try {
                constants$1.sodium_set_misuse_handler$handler$MH.invokeExact((Addressable)addr);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


